### PR TITLE
Add ability to download all fonts

### LINKED ISSUE #3: Add flag for install all fonts
Really nice script. How about exposing a flag for installing all fonts for us the crazies?

### PR DESCRIPTION
**Pull request by PyDataBlog**
Added the ability to select to install fonts. Fixes #3

### CODE REVIEW

**Review by mcarvalho1 — APPROVED** [review]

**Comment by ychaker** [comment]
@mcarvalho1 FYI: this PR broke the script because now `extension` and `github_version` are never assigned

**Comment by mcarvalho1** [comment]
@ychaker thx man, I'll fix

**Comment by PyDataBlog** [comment]
> @ychaker thx man, I'll fix 

I can look into this as well

**Comment by ychaker** [comment]
I made some fixes here: https://github.com/ychaker/nerd-fonts-downloader-script/blob/main/nf_downloader.sh

I hardcoded the versions to 3.x versions, might want to make this something the user can just provide 🤷🏽

**Comment by PyDataBlog** [comment]
> I made some fixes here: https://github.com/ychaker/nerd-fonts-downloader-script/blob/main/nf_downloader.sh
> 
> 
> 
> I hardcoded the versions to 3.x versions, might want to make this something the user can just provide 🤷🏽 

Why not make a PR?

**Comment by ychaker** [comment]
here's a PR: https://github.com/mcarvalho1/Nerd-fonts-Downloader-Script/pull/5

it makes a lot of changes, so you might want to cherry pick some 🤷🏽

**Pull request merged**
